### ISSUE TITLE
Willem's Personal Success

### ISSUE THREAD

**Issue by willemkw** [dartmouth-cs98/together#111]
# Willem Klein Wassink | Personal Goals
*what does success for this class mean to you?*
* I create a game that is fun to play and that I can show to others
* I learn how to do game design both from my successes and from my failures
* I will get as good a grade as I can in this class. If that's an A, fantastic. If not, that's still okay.

## Challenges
*what are some challenges you foresee?*

* Time crunch. We've got a lot to do, and I'm not sure we can do it all.
* My team may have some disagreements regarding design issues. This will likely not be a big challenge though. We'll be able to work it out.

**Comment by timofei7** [comment]
doing great on the goals so far! 

keep me posted on the challenges and if you need help prioritizing / working through any of the things remaining
