### ISSUE TITLE
Eitan's Personal Goals

### ISSUE THREAD

**Issue by EitanVilker** [dartmouth-cs98/together#112]
# Eitan | Personal Goals
*what does success for this class mean to you?*

* I become proficient and knowledgeable about most aspects of game development
* I create a product that is actually marketable, entertaining, and worthwhile to continue pursuing after the term ends
* I get an A/citation
* I get the chance to incorporate many or most of my design ideas into the project, giving it the kind of unique identity that I enjoy

## Challenges
*what are some challenges you foresee?*

* Large parts of the project that are essential to its feasibility have yet to be implemented, and it's not certain that we know how to do so just yet 
* I tend to take on a bunch of little features that I am confident I can make work rather than try to do something I haven't done before, and that can be an issue when the thing I haven't done is an obstacle to the product's success
* Though I managed to get some art work done by acquaintances of mine, significantly more potential art work exists and would greatly improve our product, and I don't think we can make much headway there unless we're feeling very confident in our chances of putting this game on Steam and making a profit

**Comment by timofei7** [comment]
love the goals!  i think this game could be really fun and you have a great base now. 

let me know if you'd like to chat about the challenges. happy to help think through the larger features.
