### ISSUE TITLE
Joe's Personal Success

### ISSUE THREAD

**Issue by zhangjoe99** [dartmouth-cs98/together#113]
# Joe Zhang | Personal Goals
*what does success for this class mean to you?*
* I am able to show off a cool game I have made
* I learn some new coding methods
* I am able to use the skills learned in this class to make a game from scratch
* I successfully work with others and improve my teamwork
* I am satisfied with the end product and have fun along the way

## Challenges
*what are some challenges you foresee?*
* Lots of bugs as this is a new program I have never used before (gamemaker)
* I get stuck on a bug for a long time
* I don't believe we will be able to implement all the features we have planned in the given time, so we might have to cut back on some features
* Making the features we implement look good/professional. Features we create might be working functionally but may not look good (simple gray buttons, blank background, etc)
* Maybe some merging/github errors

**Comment by timofei7** [comment]
"cool game from scratch", let's go!
